-- =============================================
-- DISABLE ALL PROBLEMATIC CONSTRAINTS
-- =============================================

-- Disable ALL source table foreign keys
ALTER TABLE SALES_FACT DISABLE CONSTRAINT SF_ORDERID_FK;
ALTER TABLE PURCHASE_FACT DISABLE CONSTRAINT PF_PURCHASEID_FK;  
ALTER TABLE LOAN_FACT DISABLE CONSTRAINT LF_LOANID_FK;
ALTER TABLE RESERVATION_FACT DISABLE CONSTRAINT RF_RESERVEID_FK;

-- Also disable any dimension FKs temporarily to avoid other issues
ALTER TABLE SALES_FACT DISABLE CONSTRAINT SF_DATE_FK;
ALTER TABLE SALES_FACT DISABLE CONSTRAINT SF_MEMBER_FK;
ALTER TABLE SALES_FACT DISABLE CONSTRAINT SF_BOOK_FK;
ALTER TABLE SALES_FACT DISABLE CONSTRAINT SF_STAFF_FK;

ALTER TABLE PURCHASE_FACT DISABLE CONSTRAINT PF_DATE_FK;
ALTER TABLE PURCHASE_FACT DISABLE CONSTRAINT PF_BOOK_FK;
ALTER TABLE PURCHASE_FACT DISABLE CONSTRAINT PF_STAFF_FK;
ALTER TABLE PURCHASE_FACT DISABLE CONSTRAINT PF_SUPPLIER_FK;

ALTER TABLE LOAN_FACT DISABLE CONSTRAINT LF_MEMBER_FK;
ALTER TABLE LOAN_FACT DISABLE CONSTRAINT LF_BOOK_FK;
ALTER TABLE LOAN_FACT DISABLE CONSTRAINT LF_STAFF_FK;
ALTER TABLE LOAN_FACT DISABLE CONSTRAINT LF_DATE_FK;

ALTER TABLE RESERVATION_FACT DISABLE CONSTRAINT RF_MEMBER_FK;
ALTER TABLE RESERVATION_FACT DISABLE CONSTRAINT RF_BOOK_FK;
ALTER TABLE RESERVATION_FACT DISABLE CONSTRAINT RF_STAFF_FK;
ALTER TABLE RESERVATION_FACT DISABLE CONSTRAINT RF_START_DATE_FK;
ALTER TABLE RESERVATION_FACT DISABLE CONSTRAINT RF_END_DATE_FK;

PROMPT All constraints disabled for bulk loading!

-- Verify all constraints are disabled
SELECT 
    table_name,
    constraint_name,
    status,
    constraint_type
FROM user_constraints 
WHERE table_name IN ('SALES_FACT', 'PURCHASE_FACT', 'LOAN_FACT', 'RESERVATION_FACT')
ORDER BY table_name, constraint_name;
